//! gen-howto: regenerate `src/howto.gen.md` from the clap surface + each
//! command's worked-example file under `docs/examples/`.
//!
//! The command TREE (groups, names, about, flags) comes from `carpenter::app::cli()`
//! (recursed into nested groups). The EXAMPLE blocks come from
//! `docs/examples/<module>/<name>.md`, keyed `<module>::<name>` so groups with
//! same-named leaves (e.g. `course::create` vs `lesson::create`) don't collide.
//! That file is the single source — build.rs enforces its presence per command fn
//! (adr/007 update), and nothing is scraped from `///` anymore.

use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

use carpenter::app;

/// Write the generated manual to `src/howto.gen.md`.
pub fn run() -> anyhow::Result<()> {
    let manual = generate();
    let path = crate::paths::workspace_root().join("src/howto.gen.md");
    std::fs::write(&path, manual)?;
    println!("gen-howto: wrote {}", path.display());
    Ok(())
}

/// Produce the manual text (clap surface + each command's fenced example).
pub fn generate() -> String {
    let root = app::cli();
    let examples = collect_examples();
    let global_names: HashSet<String> = root
        .get_arguments()
        .filter_map(|a| a.get_long().map(|l| l.to_string()))
        .collect();

    let mut out = String::new();
    out.push_str("# carpenter — howto\n\n");
    out.push_str("<!-- Generated by `cargo xtask gen-howto`. Do not hand-edit. -->\n\n");

    out.push_str("## global flags\n\n");
    for f in root.get_arguments().filter(|a| !a.is_positional()) {
        push_flag(&mut out, f);
    }
    out.push('\n');

    for sub in root.get_subcommands() {
        render(sub, sub.get_name(), 2, &mut out, &examples, &global_names);
    }
    out
}

/// Render one command (group or leaf). `module` is the top-level command name
/// (the source file stem), used to look up `<module>::<leaf>` examples.
fn render(
    cmd: &clap::Command,
    module: &str,
    depth: usize,
    out: &mut String,
    examples: &HashMap<String, String>,
    global_names: &HashSet<String>,
) {
    let name = cmd.get_name();
    let heading = "#".repeat(depth);
    out.push_str(&format!("{heading} {name}\n\n"));
    let about = cmd.get_about().map(|s| s.to_string()).unwrap_or_default();
    if !about.is_empty() {
        out.push_str(&format!("{about}\n\n"));
    }
    let own_flags: Vec<_> = cmd
        .get_arguments()
        .filter(|a| !a.is_positional())
        .filter(|a| {
            a.get_long()
                .map(|l| !global_names.contains(l))
                .unwrap_or(true)
        })
        .collect();
    if own_flags.is_empty() {
        out.push_str("_flags: none_\n\n");
    } else {
        for f in &own_flags {
            push_flag(out, f);
        }
        out.push('\n');
    }
    let subs: Vec<_> = cmd.get_subcommands().collect();
    if subs.is_empty() {
        if let Some(ex) = examples.get(&format!("{module}::{name}")) {
            out.push_str(ex.trim());
            out.push_str("\n\n");
        }
    } else {
        for child in subs {
            render(child, module, depth + 1, out, examples, global_names);
        }
    }
}

fn push_flag(out: &mut String, f: &clap::Arg) {
    let short = f.get_short().map(|s| format!("-{s}, ")).unwrap_or_default();
    let long = f.get_long().map(|l| format!("--{l}")).unwrap_or_default();
    let value = f
        .get_value_names()
        .map(|vs| vs.join(","))
        .map(|v| format!(" <{v}>"))
        .unwrap_or_default();
    let help = f.get_help().map(|h| h.to_string()).unwrap_or_default();
    out.push_str(&format!("- `{short}{long}{value}` — {help}\n"));
}

fn collect_examples() -> HashMap<String, String> {
    let dir = crate::paths::workspace_root().join("docs/examples");
    let mut map = HashMap::new();
    for path in walk_md(&dir) {
        let module = path
            .parent()
            .and_then(|p| p.file_name())
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_default();
        let name = path
            .file_stem()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_default();
        if let Ok(text) = std::fs::read_to_string(&path) {
            map.insert(format!("{module}::{name}"), text);
        }
    }
    map
}

fn walk_md(dir: &Path) -> Vec<PathBuf> {
    // Layout is exactly two levels: <dir>/<module>/<name>.md
    let mut out = Vec::new();
    let Ok(modules) = std::fs::read_dir(dir) else {
        return out;
    };
    for m in modules.flatten() {
        let mp = m.path();
        if !mp.is_dir() {
            continue;
        }
        let Ok(entries) = std::fs::read_dir(&mp) else {
            continue;
        };
        for e in entries.flatten() {
            let p = e.path();
            if p.extension().map(|x| x == "md").unwrap_or(false) {
                out.push(p);
            }
        }
    }
    out
}

#[cfg(test)]
#[test]
fn howto_gen_md_is_fresh() {
    let generated = generate();
    let committed = include_str!("../../src/howto.gen.md");
    assert_eq!(
        generated, committed,
        "src/howto.gen.md is stale; run `cargo xtask gen-howto`"
    );
}
